/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MyAgentsRouteImport } from './routes/my-agents'
import { Route as MomentsRouteImport } from './routes/moments'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BattlesRouteImport } from './routes/battles'
import { Route as AutonomousRouteImport } from './routes/autonomous'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as IndexRouteImport } from './routes/index'

const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MyAgentsRoute = MyAgentsRouteImport.update({
  id: '/my-agents',
  path: '/my-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const MomentsRoute = MomentsRouteImport.update({
  id: '/moments',
  path: '/moments',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BattlesRoute = BattlesRouteImport.update({
  id: '/battles',
  path: '/battles',
  getParentRoute: () => rootRouteImport,
} as any)
const AutonomousRoute = AutonomousRouteImport.update({
  id: '/autonomous',
  path: '/autonomous',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/autonomous': typeof AutonomousRoute
  '/battles': typeof BattlesRoute
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/moments': typeof MomentsRoute
  '/my-agents': typeof MyAgentsRoute
  '/settings': typeof SettingsRoute
  '/training': typeof TrainingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/autonomous': typeof AutonomousRoute
  '/battles': typeof BattlesRoute
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/moments': typeof MomentsRoute
  '/my-agents': typeof MyAgentsRoute
  '/settings': typeof SettingsRoute
  '/training': typeof TrainingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/autonomous': typeof AutonomousRoute
  '/battles': typeof BattlesRoute
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/moments': typeof MomentsRoute
  '/my-agents': typeof MyAgentsRoute
  '/settings': typeof SettingsRoute
  '/training': typeof TrainingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/autonomous'
    | '/battles'
    | '/dashboard'
    | '/inventory'
    | '/leaderboard'
    | '/moments'
    | '/my-agents'
    | '/settings'
    | '/training'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/autonomous'
    | '/battles'
    | '/dashboard'
    | '/inventory'
    | '/leaderboard'
    | '/moments'
    | '/my-agents'
    | '/settings'
    | '/training'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/autonomous'
    | '/battles'
    | '/dashboard'
    | '/inventory'
    | '/leaderboard'
    | '/moments'
    | '/my-agents'
    | '/settings'
    | '/training'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  AutonomousRoute: typeof AutonomousRoute
  BattlesRoute: typeof BattlesRoute
  DashboardRoute: typeof DashboardRoute
  InventoryRoute: typeof InventoryRoute
  LeaderboardRoute: typeof LeaderboardRoute
  MomentsRoute: typeof MomentsRoute
  MyAgentsRoute: typeof MyAgentsRoute
  SettingsRoute: typeof SettingsRoute
  TrainingRoute: typeof TrainingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-agents': {
      id: '/my-agents'
      path: '/my-agents'
      fullPath: '/my-agents'
      preLoaderRoute: typeof MyAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moments': {
      id: '/moments'
      path: '/moments'
      fullPath: '/moments'
      preLoaderRoute: typeof MomentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battles': {
      id: '/battles'
      path: '/battles'
      fullPath: '/battles'
      preLoaderRoute: typeof BattlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autonomous': {
      id: '/autonomous'
      path: '/autonomous'
      fullPath: '/autonomous'
      preLoaderRoute: typeof AutonomousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  AutonomousRoute: AutonomousRoute,
  BattlesRoute: BattlesRoute,
  DashboardRoute: DashboardRoute,
  InventoryRoute: InventoryRoute,
  LeaderboardRoute: LeaderboardRoute,
  MomentsRoute: MomentsRoute,
  MyAgentsRoute: MyAgentsRoute,
  SettingsRoute: SettingsRoute,
  TrainingRoute: TrainingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
